export enum ConfigEnum {
  DB_PORT = 'DB_PORT',
  DB_PASS = 'DB_PASS',
  DB_USER = 'DB_USER',
  DB_NAME = 'DB_NAME',
  HOST = 'HOST',
  TYPEORM_CONFIG = 'TYPEORM_CONFIG',
  DEFAULT_USER_PASSWORD = 'DEFAULT_USER_PASSWORD',
  DEFAULT_USER_NAME = 'DEFAULT_USER_NAME',
  DEFAULT_USER_EMAIL = 'DEFAULT_USER_EMAIL',
}
